// IDB-6D Fit-Test Coupon
// Generated by DIY Lamp Builder
// Print this coupon before the full shell to validate M3 holes, diffuser slot, cable exit, and engraving.

font = "Liberation Sans"; // font() may not render on all OpenSCAD builds; use for reference only

module m3_hole_ladder() {
  // M3 hole diameter test: 3.0 / 3.2 / 3.4 mm
  for (i = [0:2]) {
    d = 3.0 + i * 0.2;
    translate([i * 10, 0, 0])
      cylinder(d = d, h = 10, center = true, $fn = 32);
  }
}

module diffuser_slot_ladder() {
  // Diffuser slot width test: 17.8 / 18.0 / 18.2 / 18.4 mm
  widths = [17.8, 18.0, 18.2, 18.4];
  for (i = [0:3]) {
    translate([i * 22, 0, 0])
      cube([widths[i], 4, 8], center = true);
  }
}

module cable_exit_test() {
  // Cable exit radius test: 4 / 5 mm
  for (i = [0:1]) {
    r = 4 + i;
    translate([i * 12, 0, 0])
      cylinder(r = r, h = 10, center = true, $fn = 32);
  }
}

module engraving_sample() {
  // Small text sample to check legibility after FDM
  linear_extrude(height = 0.3)
    text("IDB-6D", size = 3, font = font, halign = "center", valign = "center");
}

module fit_test_coupon() {
  difference() {
    union() {
      // base plate
      cube([70, 40, 2], center = true);
      // cable exit bosses
      translate([-20, 12, 3]) cylinder(r = 6, h = 4, center = true, $fn = 32);
      translate([8, 12, 3]) cylinder(r = 6, h = 4, center = true, $fn = 32);
    }
    // M3 holes
    translate([-20, -10, 0]) m3_hole_ladder();
    // diffuser slots
    translate([-22, 2, 0]) diffuser_slot_ladder();
    // cable exits
    translate([-20, 12, 3]) cable_exit_test();
    // engraving
    translate([18, -10, 1]) engraving_sample();
  }
}

fit_test_coupon();
